"""Tests for the GWAS PRS calculator."""
import argparse
import json
import math
import sys
import time
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

# Add skill directory to path
SKILL_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(SKILL_DIR))

import gwas_prs

FIXTURES = Path(__file__).resolve().parent / "fixtures"


# --------------------------------------------------------------------------- #
# TestGenotypeParser
# --------------------------------------------------------------------------- #


class TestGenotypeParser:
    """Tests for genotype file format detection and parsing."""

    def test_detect_23andme_format(self):
        """detect_format identifies 23andMe-style header lines."""
        lines = [
            "# This data file generated by 23andMe",
            "#",
            "# rsid\tchromosome\tposition\tgenotype",
            "rs100001\t1\t100000\tAG",
        ]
        fmt = gwas_prs.detect_format(lines)
        assert fmt == "23andme"

    def test_detect_ancestry_format(self):
        """detect_format identifies AncestryDNA-style header lines."""
        lines = [
            "#AncestryDNA raw data download",
            "RSID,CHROMOSOME,POSITION,ALLELE1,ALLELE2",
            "rs100001,1,100000,A,G",
        ]
        fmt = gwas_prs.detect_format(lines)
        assert fmt == "ancestry"

    def test_parse_23andme_file(self):
        """parse_genotype_file returns all valid SNPs from a 23andMe file."""
        fmt, total, genotypes = gwas_prs.parse_genotype_file(
            FIXTURES / "mock_genotype_23andme.txt"
        )
        assert fmt == "23andme"
        assert total == 6
        assert "rs100001" in genotypes
        assert genotypes["rs100001"] == "AG"

    def test_parse_genotype_skips_invalid(self, tmp_path):
        """Lines with '--' genotypes are filtered; '00' and valid genotypes are kept.

        The shared parser (clawbio.common.parsers) strips '--' entries but
        preserves '00' (ambiguous no-calls that downstream scoring handles
        by yielding dosage 0). Valid genotypes are always kept.
        """
        bad_file = tmp_path / "bad_geno.txt"
        bad_file.write_text(
            "# This data file generated by 23andMe\n"
            "#\n"
            "# rsid\tchromosome\tposition\tgenotype\n"
            "rs000001\t1\t100000\t--\n"
            "rs000002\t2\t200000\t00\n"
            "rs000003\t3\t300000\tAG\n"
        )
        fmt, total, genotypes = gwas_prs.parse_genotype_file(bad_file)
        assert "rs000001" not in genotypes  # '--' is filtered
        assert "rs000003" in genotypes      # valid genotype kept
        assert total >= 1


# --------------------------------------------------------------------------- #
# TestScoringFileParser
# --------------------------------------------------------------------------- #


class TestScoringFileParser:
    """Tests for PGS Catalog scoring file parsing."""

    def test_parse_scoring_file(self):
        """parse_scoring_file returns all 5 variants with correct fields."""
        variants = gwas_prs.parse_scoring_file(
            FIXTURES / "mock_scoring_file.txt"
        )
        assert len(variants) == 5
        first = variants[0]
        assert first["rsid"] == "rs100001"
        assert first["effect_allele"] == "A"
        assert float(first["effect_weight"]) == pytest.approx(0.15)

    def test_parse_scoring_file_metadata(self):
        """Metadata comment lines (starting with #) are not returned as variants."""
        variants = gwas_prs.parse_scoring_file(
            FIXTURES / "mock_scoring_file.txt"
        )
        # Only data rows, no comment lines
        for v in variants:
            assert not v["rsid"].startswith("#")

    def test_parse_scoring_file_missing_rsid(self, tmp_path):
        """Rows without a valid rsID are skipped."""
        score_file = tmp_path / "no_rsid.txt"
        score_file.write_text(
            "#pgs_id=PGS000099\n"
            "rsID\tchr_name\tchr_position\teffect_allele\tother_allele\teffect_weight\n"
            "rs100001\t1\t100000\tA\tG\t0.15\n"
            "\t2\t200000\tT\tC\t0.08\n"
            ".\t3\t300000\tG\tA\t-0.12\n"
        )
        variants = gwas_prs.parse_scoring_file(score_file)
        assert len(variants) == 1
        assert variants[0]["rsid"] == "rs100001"


# --------------------------------------------------------------------------- #
# TestAlleleDosage
# --------------------------------------------------------------------------- #


class TestAlleleDosage:
    """Tests for allele dosage computation."""

    def test_dosage_homozygous_effect(self):
        """Homozygous for the effect allele yields dosage 2."""
        assert gwas_prs.compute_allele_dosage("AA", "A") == 2

    def test_dosage_heterozygous(self):
        """Heterozygous genotype yields dosage 1."""
        assert gwas_prs.compute_allele_dosage("AG", "A") == 1

    def test_dosage_homozygous_other(self):
        """Homozygous for the other allele yields dosage 0."""
        assert gwas_prs.compute_allele_dosage("GG", "A") == 0

    def test_dosage_hemizygous(self):
        """Single-allele (hemizygous, e.g. chrX male) yields dosage 1."""
        assert gwas_prs.compute_allele_dosage("A", "A") == 1


# --------------------------------------------------------------------------- #
# TestPRSCalculation
# --------------------------------------------------------------------------- #


class TestPRSCalculation:
    """Tests for the core PRS calculation logic."""

    def test_calculate_prs_basic(self):
        """Known genotypes + weights produce a non-zero raw PRS."""
        _fmt, _n, genotypes = gwas_prs.parse_genotype_file(
            FIXTURES / "mock_genotype_23andme.txt"
        )
        variants = gwas_prs.parse_scoring_file(
            FIXTURES / "mock_scoring_file.txt"
        )
        result = gwas_prs.calculate_prs(genotypes, variants)
        assert "raw_score" in result
        assert isinstance(result["raw_score"], float)
        assert result["raw_score"] != 0.0

    def test_calculate_prs_overlap(self):
        """Overlap fraction is correctly calculated."""
        _fmt, _n, genotypes = gwas_prs.parse_genotype_file(
            FIXTURES / "mock_genotype_23andme.txt"
        )
        variants = gwas_prs.parse_scoring_file(
            FIXTURES / "mock_scoring_file.txt"
        )
        result = gwas_prs.calculate_prs(genotypes, variants)
        # All 5 scoring variants are present in the genotype file
        assert result["variants_used"] == 5
        assert result["variants_total"] == 5
        assert result["overlap_fraction"] == pytest.approx(1.0)

    def test_calculate_prs_no_overlap(self):
        """Zero score when no scoring SNPs match the genotype file."""
        genotypes = {"rs999999": "AA"}
        variants = gwas_prs.parse_scoring_file(
            FIXTURES / "mock_scoring_file.txt"
        )
        result = gwas_prs.calculate_prs(genotypes, variants)
        assert result["variants_used"] == 0
        assert result["raw_score"] == 0.0

    def test_calculate_prs_partial_overlap(self):
        """Subset of SNPs match — only matched ones contribute."""
        genotypes = {
            "rs100001": "AG",
            "rs100003": "AA",
        }
        variants = gwas_prs.parse_scoring_file(
            FIXTURES / "mock_scoring_file.txt"
        )
        result = gwas_prs.calculate_prs(genotypes, variants)
        assert result["variants_used"] == 2
        assert result["variants_total"] == 5
        assert result["overlap_fraction"] == pytest.approx(0.4)


# --------------------------------------------------------------------------- #
# TestPercentileEstimation
# --------------------------------------------------------------------------- #


class TestPercentileEstimation:
    """Tests for Z-score to percentile conversion and risk categories."""

    def test_percentile_from_z_zero(self):
        """Z-score of 0.0 corresponds to approximately the 50th percentile."""
        pct = gwas_prs._percentile_from_z(0.0)
        assert pct == pytest.approx(50.0, abs=0.5)

    def test_percentile_from_z_positive(self):
        """Z-score of 1.96 corresponds to approximately the 97.5th percentile."""
        pct = gwas_prs._percentile_from_z(1.96)
        assert pct == pytest.approx(97.5, abs=0.5)

    def test_assign_risk_category_low(self):
        """Percentile 10 is classified as 'Low'."""
        cat = gwas_prs._assign_risk_category(10)
        assert cat == "Low"

    def test_assign_risk_category_average(self):
        """Percentile 50 is classified as 'Average'."""
        cat = gwas_prs._assign_risk_category(50)
        assert cat == "Average"


# --------------------------------------------------------------------------- #
# TestPGSCatalogClient
# --------------------------------------------------------------------------- #


class TestPGSCatalogClient:
    """Tests for PGS Catalog REST API client (mocked)."""

    def test_search_traits(self, tmp_path):
        """search_traits returns a list of matching trait dicts."""
        mock_data = json.loads(
            (FIXTURES / "mock_trait_search.json").read_text()
        )
        mock_response = MagicMock()
        mock_response.status_code = 200
        mock_response.json.return_value = mock_data

        with patch.object(gwas_prs.requests.Session, "get", return_value=mock_response):
            client = gwas_prs.PGSCatalogClient(
                cache_dir=tmp_path / "cache", use_cache=False
            )
            traits = client.search_traits("diabetes")
            assert len(traits) == 2
            assert traits[0]["id"] == "EFO_0001360"

    def test_get_score_metadata(self, tmp_path):
        """get_score_metadata returns a score dict with expected keys."""
        mock_data = json.loads(
            (FIXTURES / "mock_score_metadata.json").read_text()
        )
        mock_response = MagicMock()
        mock_response.status_code = 200
        mock_response.json.return_value = mock_data

        with patch.object(gwas_prs.requests.Session, "get", return_value=mock_response):
            client = gwas_prs.PGSCatalogClient(
                cache_dir=tmp_path / "cache", use_cache=False
            )
            score = client.get_score_metadata("PGS000013")
            assert score["id"] == "PGS000013"
            assert score["variants_number"] == 8

    def test_rate_limiting(self, tmp_path):
        """_throttle introduces a delay between rapid calls."""
        client = gwas_prs.PGSCatalogClient(
            cache_dir=tmp_path / "cache", use_cache=False
        )
        client._last_request_time = time.time()
        t0 = time.time()
        client._throttle()
        elapsed = time.time() - t0
        # Should have waited at least some time (rate limit interval)
        assert elapsed >= 0.4


# --------------------------------------------------------------------------- #
# TestReportGeneration
# --------------------------------------------------------------------------- #


class TestReportGeneration:
    """Tests for the Markdown report generator."""

    def _make_sample_results(self):
        """Helper to build minimal results list for report generation."""
        return [
            {
                "pgs_id": "PGS000013",
                "trait": "Type 2 diabetes",
                "prs": {
                    "raw_score": 0.57,
                    "variants_used": 7,
                    "variants_total": 8,
                    "variants_missing": 1,
                    "overlap_fraction": 0.875,
                    "per_variant": [],
                },
                "percentile_info": {
                    "percentile": 88.5,
                    "method": "curated_reference",
                    "risk_category": "Elevated",
                    "z_score": 1.2,
                    "reference_population": "EUR",
                },
                "metadata": {"publication": "Vassy et al. (2014)"},
            },
            {
                "pgs_id": "PGS000004",
                "trait": "Coronary artery disease",
                "prs": {
                    "raw_score": 0.32,
                    "variants_used": 40,
                    "variants_total": 46,
                    "variants_missing": 6,
                    "overlap_fraction": 0.87,
                    "per_variant": [],
                },
                "percentile_info": {
                    "percentile": 38.2,
                    "method": "curated_reference",
                    "risk_category": "Average",
                    "z_score": -0.3,
                    "reference_population": "EUR",
                },
                "metadata": {"publication": "Abraham et al. (2016)"},
            },
        ]

    def _make_input_info(self):
        return {
            "filepath": "test_patient.txt",
            "format": "23andme",
            "total_snps": 600000,
        }

    def _make_args(self):
        return argparse.Namespace(build="GRCh37")

    def test_generate_report_contains_header(self):
        """Report contains the expected top-level heading."""
        results = self._make_sample_results()
        report = gwas_prs.generate_report(
            results, self._make_input_info(), self._make_args()
        )
        assert "# GWAS Polygenic Risk Score Report" in report

    def test_generate_report_contains_disclaimer(self):
        """Report contains the safety disclaimer text."""
        results = self._make_sample_results()
        report = gwas_prs.generate_report(
            results, self._make_input_info(), self._make_args()
        )
        assert "ClawBio is a research and educational tool" in report

    def test_generate_report_score_table(self):
        """Report includes a summary table with PGS IDs."""
        results = self._make_sample_results()
        report = gwas_prs.generate_report(
            results, self._make_input_info(), self._make_args()
        )
        assert "PGS000013" in report
        assert "PGS000004" in report
        assert "Type 2 diabetes" in report
