# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

# set work directory
WORKDIR /app

# Install build dependencies and git (needed for AlphaGenome)
RUN apt-get update && apt-get install -y --no-install-recommends gcc build-essential git && rm -rf /var/lib/apt/lists/*

# Copy requirements (pyproject.toml, etc.)
COPY pyproject.toml .
COPY README.md .
COPY LICENSE .

# Copy source code
COPY src ./src
COPY tests ./tests
COPY Makefile .
COPY tox.ini .

# Install the package with worker dependencies
RUN pip install --upgrade pip && pip install .[worker]

# Clone and install AlphaGenome
RUN git clone https://github.com/google-deepmind/alphagenome.git /tmp/alphagenome && \
    pip install /tmp/alphagenome && \
    rm -rf /tmp/alphagenome

# Expose port for remote MCP connections
EXPOSE 8000

# Set default mode to worker, but allow it to be overridden
ENV MCP_MODE=stdio

# Run the MCP server with configurable mode
CMD ["sh", "-c", "biomcp run --mode ${MCP_MODE}"]
