# COPYRIGHT NOTICE
# This file is part of the "Universal Biomedical Skills" project.
# Copyright (c) 2026 MD BABU MIA, PhD <md.babu.mia@mssm.edu>
# All Rights Reserved.
#
# This code is proprietary and confidential.
# Unauthorized copying of this file, via any medium is strictly prohibited.
#
# Provenance: Authenticated by MD BABU MIA

from opentrons import protocol_api

metadata = {
    'protocolName': 'LLM Generated Serial Dilution',
    'author': 'Opentrons Agent <md.babu.mia@mssm.edu>',
    'description': 'Automated serial dilution protocol generated by AI agent',
    'apiLevel': '2.13'
}

def run(protocol: protocol_api.ProtocolContext):
    # --- Labware Setup ---
    # Tiprack on Slot 1
    tiprack = protocol.load_labware('opentrons_96_tiprack_300ul', 1)
    
    # 96-well plate on Slot 2
    plate = protocol.load_labware('corning_96_wellplate_360ul_flat', 2)
    
    # --- Pipette Setup ---
    # P300 Single Gen2 on Right Mount
    p300 = protocol.load_instrument('p300_single_gen2', 'right', tip_racks=[tiprack])
    
    # --- Protocol Logic ---
    # Example: Serial Dilution across a row
    # Row A: A1 is source (conc), A2-A12 are diluents
    
    row = plate.rows()[0] # Row A
    
    # Transfer 100uL from previous well to next, mix 3x
    transfer_vol = 100
    mix_reps = 3
    mix_vol = 100
    
    p300.pick_up_tip()
    
    for i in range(len(row) - 1):
        source = row[i]
        dest = row[i+1]
        
        # Transfer
        p300.transfer(
            transfer_vol,
            source,
            dest,
            mix_after=(mix_reps, mix_vol),
            new_tip='never' # Keep same tip for serial dilution down the gradient
        )
        
    p300.drop_tip()

    protocol.comment("Serial dilution complete.")

__AUTHOR_SIGNATURE__ = "9a7f3c2e-MD-BABU-MIA-2026-MSSM-SECURE"
